config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:destroy, :edit, :update, :new, :index] do
    resources :bookmarks, only: [:create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @movies = Movie.all

    # @movie_selection = @movies.select { |movie| movie.id == params[:bookmark][:movie_id]}
    @movie_selection = params[:bookmark][:movie_id]
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new

    @movie_selection.each do |movie_index|
      bookmark = Bookmark.new
      movie = Movie.find(movie_index)
      bookmark.movie = movie
      bookmark.list = @list
      bookmark.save

    end
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @new_list = List.new
    @list = List.new
  end

  def show
    @new_list = List.new
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: 'List was successfully created'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="<%= root_path %>">
    <img src="https://www.freeiconspng.com/thumbs/popcorn-png/popcorn-png-3.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a type="button" class="nav-link" data-toggle="modal" data-target="#exampleModal">
           New list
        </a>
      </li>
    </ul>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> New List</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="new-movie-form">
          <%= simple_form_for(@new_list) do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Create new list", class: "btn btn-lg btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<%= render 'navbar'%>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://localfresh.com/wp-content/uploads/iStock-1281139645-1024x683.jpg);">
  <div class="container">
    <div class="row justify-content-end pr-4 align-items-end">
      <h1 id="banner-typed-text"></h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="row justify-content-between align-items-end mt-5 mb-3">
    <h2 class="col-3">Your lists</h2>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Create a new list!
    </button>
  </div>

  <div class = "row">
    <% @lists.each do |list| %>
      <div class="movie-card col-6 col-lg-4 p-3 mb-3">
        <%= link_to list_path(list), class: "link-unstyled h3 list-group-item p-0" do%>
          <%# unless list.movies.empty? %>
          <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill, style: "margin:0; width: 100%; border-top-left-radius: 8px; border-top-right-radius: 8px;"%>
          <!-- <img src="<%=list.movies.sample.poster_url %>", style = "margin:0; width: 100%; border-top-left-radius: 8px; border-top-right-radius: 8px;"> -->
          <%# end %>
          <div class="text-center p-3" style="border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;">
          <%= list.name%>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> New List</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="new-movie-form">
          <%= simple_form_for(@list) do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Create new list", class: "btn btn-lg btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render 'navbar'%>
<div class="row justify-content-center mt-4">
 <%= cl_image_tag @list.photo.key, height: 300, width: 300, crop: :fill%>
 </div>
<div class="container">
  <h1 class="text-center mt-4 mb-0"><%= @list.name %></h1>
  <div class="row justify-content-end">
    <!-- <button class="btn btn-primary mt-0 mb-0" id="new-movie-button" style="">Add new movie to list</button> -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newMovieModal">
      Add new movie to list
    </button>
  </div>
  <div class = "row">
    <% @list.movies.each do |movie| %>
      <div class="movie-card col-6 col-lg-4 mt-3 p-3 border">
        <div class="movie-container row flex-column">
          <%= image_tag "#{movie.poster_url}", alt: "Poster", width: 200, class: "col"%>
          <p class="col text-center h5 p-2">
            <%= movie.title%>
            <%= movie.rating %>
            <%= link_to bookmark_path(@list.bookmarks.select {|bookmark| bookmark.movie_id == movie.id}[0]), method: :delete do%>
              <i class="fas fa-trash"></i>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div class="modal fade" id="newMovieModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Select Movie</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="new-movie-form">
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.input :comment %>
            <%= f.association :movie, input_html: {multiple: true, class: "multiple-select"}, include_hidden: false %>
            <%= f.submit "Add Movie" , class: "btn btn-lg btn-primary" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>